development:
  adapter: postgresql
  database: learn_rails_development
  username: wahyubucil
  password: null
  encoding: unicode
  host: localhost
  pool: 5
test:
  adapter: postgresql
  database: learn_rails_test
  username: wahyubucil
  password: null
  encoding: unicode
  host: localhost
  pool: 5
production:
  adapter: postgresql
  database: learn_rails_production
  username: wahyubucil
  password: null
  encoding: unicode
  host: localhost
  pool: 5